version: '3.8'

services:
  smart-radar:
    build:
      context: .
      dockerfile: Dockerfile.smart
    container_name: smart-news-radar
    restart: unless-stopped
    
    # 环境变量（可选，用于通知配置）
    environment:
      # 如果需要通知功能，设置以下环境变量
      # FEISHU_WEBHOOK_URL: ""
      # WEWORK_WEBHOOK_URL: ""
      # DINGTALK_WEBHOOK_URL: ""
      # TELEGRAM_BOT_TOKEN: ""
      # TELEGRAM_CHAT_ID: ""
      
      # 运行模式
      RUN_MODE: "manual"  # manual/cron
      TZ: "Asia/Shanghai"
    
    # 数据持久化
    volumes:
      - ./output:/app/output
      - ./learning_data:/app/learning_data
      - ./smart_config.yaml:/app/smart_config.yaml:ro
    
    # 定时执行（如果需要）
    # 可以通过cron或者在容器内使用定时任务
    labels:
      - "com.docker.compose.project=smart-news-radar"
      - "description=AI-driven news keyword discovery system"
    
    # 资源限制
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    
    # 网络配置
    networks:
      - smart-radar-net

  # 可选：添加一个简单的Web服务器来展示HTML报告
  web-server:
    image: nginx:alpine
    container_name: smart-radar-web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./output:/usr/share/nginx/html/reports:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - smart-radar-net
    depends_on:
      - smart-radar

networks:
  smart-radar-net:
    driver: bridge

# 如果需要定时执行，可以使用以下配置
# 或者在宿主机上设置cron任务