# SmartNewsRadar Enhanced - 增强版配置
# 支持多种数据源：newsnow API + RSS订阅 + 网页抓取

# 数据获取配置
data_sources:
  # 启用增强模式（多源获取）
  enhanced_mode: true
  
  # 数据源超时设置（秒）
  timeout: 30
  
  # 并发请求数限制 - 从10增加到20以支持更多并发源
  concurrent_limit: 20
  
  # 源配置 - NewNow API（主要源）
  newsnow_api:
    enabled: true
    sources:
      # 社交媒体平台 (6个)
      - id: "weibo"
        name: "微博热搜"
      - id: "douyin"
        name: "抖音热搜"
      - id: "kuaishou"
        name: "快手热搜"
      - id: "tieba"
        name: "百度贴吧"
      - id: "coolapk"
        name: "酷安社区"
      - id: "hupu"
        name: "虎扑社区"
      
      # 传统新闻媒体 (5个)
      - id: "toutiao"
        name: "今日头条"
      - id: "ifeng"
        name: "凤凰网"
      - id: "thepaper"
        name: "澎湃新闻"
      - id: "cankaoxiaoxi"
        name: "参考消息"
      - id: "zaobao"
        name: "联合早报"
      
      # 财经金融媒体 (7个)
      - id: "wallstreetcn-hot"
        name: "华尔街见闻"
      - id: "_36kr"
        name: "36氪"
      - id: "xueqiu"
        name: "雪球"
      - id: "gelonghui"
        name: "格隆汇"
      - id: "fastbull"
        name: "快牛财经"
      - id: "jin10"
        name: "金十数据"
      - id: "mktnews"
        name: "市场新闻"
      
      # 科技数码媒体 (6个)
      - id: "ithome"
        name: "IT之家"
      - id: "juejin"
        name: "掘金"
      - id: "sspai"
        name: "少数派"
      - id: "smzdm"
        name: "什么值得买"
      - id: "chongbuluo"
        name: "虫部落"
      - id: "pcbeta"
        name: "远景论坛"
      
      # 技术开发社区 (4个)
      - id: "github"
        name: "GitHub趋势"
      - id: "v2ex"
        name: "V2EX"
      - id: "linuxdo"
        name: "Linux Do"
      - id: "hackernews"
        name: "Hacker News"
      
      # 知识学习平台 (3个)
      - id: "zhihu"
        name: "知乎热榜"
      - id: "nowcoder"
        name: "牛客网"
      - id: "kaopu"
        name: "考普网"
      
      # 娱乐视频平台 (2个)
      - id: "bilibili-hot-search"
        name: "B站热搜"
      - id: "ghxi"
        name: "光华喜"
      
      # 其他特色平台 (5个)
      - id: "baidu"
        name: "百度热搜"
      - id: "producthunt"
        name: "Product Hunt"
      - id: "solidot"
        name: "Solidot"
      - id: "sputniknewscn"
        name: "俄罗斯卫星通讯社"
      - id: "cls"
        name: "财联社"

  # RSS订阅源（补充源）
  rss_feeds:
    enabled: true
    sources:
      # 综合新闻媒体
      - name: "新浪新闻"
        url: "http://rss.sina.com.cn/news/allnews/sports.xml"
        enabled: true
      - name: "新浪头条"
        url: "http://rss.sina.com.cn/news/marquee/ddt.xml"
        enabled: true
      - name: "网易新闻"
        url: "http://news.163.com/special/00011K6L/rss_newstop.xml"
        enabled: true
      - name: "网易科技"
        url: "http://tech.163.com/special/00097UHL/tech_datalist.xml"
        enabled: true
      - name: "腾讯新闻"
        url: "https://news.qq.com/newsgn/rss_newsgn.xml"
        enabled: true
      - name: "搜狐新闻"
        url: "http://news.sohu.com/rss/guonei.xml"
        enabled: true
      - name: "凤凰网"
        url: "https://news.ifeng.com/rss/index.xml"
        enabled: true
      
      # 财经金融媒体
      - name: "财新网"
        url: "http://rss.caixin.com/blog/rss.xml"
        enabled: true
      - name: "36氪"
        url: "https://36kr.com/feed"
        enabled: true
      - name: "虎嗅"
        url: "https://www.huxiu.com/rss/0.xml"
        enabled: true  # 改为启用
      - name: "每日经济新闻"
        url: "https://www.nbd.com.cn/rss/"
        enabled: true
      - name: "第一财经"
        url: "https://m.yicai.com/rss/yicaihome.xml"
        enabled: true
      - name: "东方财富网"
        url: "https://finance.eastmoney.com/rss/default.xml"
        enabled: true
      - name: "金融界"
        url: "https://www.jrj.com.cn/rss/jryw.xml"
        enabled: true
      
      # 科技媒体
      - name: "CNBeta"
        url: "https://www.cnbeta.com/backend.php"
        enabled: true
      - name: "IT之家科技"
        url: "https://rss.ithome.com/rss/ithome.xml"
        enabled: true
      - name: "爱范儿"
        url: "https://www.ifanr.com/feed"
        enabled: true
      - name: "少数派"
        url: "https://sspai.com/feed"
        enabled: true
      
      # 权威媒体
      - name: "央视新闻"
        url: "https://news.cctv.com/rss/news.shtml"
        enabled: true
      - name: "界面新闻"
        url: "https://a.jiemian.com/index.php/Api/Rss/getList/cid/1"
        enabled: true
      - name: "中国日报网"
        url: "https://www.ecns.cn/rss/rss.xml"
        enabled: true
      - name: "中国经济周刊"
        url: "https://www.ceweekly.cn/feed/"
        enabled: true
      
      # 国际媒体（中文）
      - name: "环球时报"
        url: "https://www.globaltimes.cn/rss/china.xml"
        enabled: true
      - name: "南华早报"
        url: "https://www.scmp.com/rss/4/feed"
        enabled: true
      - name: "路透中文网"
        url: "https://cn.reuters.com/rssFeed/CNAheadlinesNews"
        enabled: true

  # 网页抓取源（备用源）
  web_scraping:
    enabled: false  # 改为禁用，防止被反爬虫
    sources:
      # 综合新闻
      - name: "腾讯新闻"
        url: "https://news.qq.com/"
        selector: ".Q-tpWrap .linkto"
        enabled: true
      - name: "搜狐新闻"
        url: "https://news.sohu.com/"
        selector: ".news-text h4 a"
        enabled: true
      - name: "凤凰网"
        url: "https://news.ifeng.com/"
        selector: ".news_1 a"
        enabled: true
      - name: "界面新闻"
        url: "https://www.jiemian.com/"
        selector: ".news-list .news-item h3 a"
        enabled: true
      - name: "人民网"
        url: "http://www.people.com.cn/"
        selector: ".headlineNews a"
        enabled: true
      - name: "新华网"
        url: "http://www.xinhuanet.com/"
        selector: ".news-list li a"
        enabled: true
      - name: "中国网"
        url: "https://www.china.com.cn/"
        selector: ".headline a"
        enabled: true
      - name: "央视新闻"
        url: "https://news.cctv.com/"
        selector: ".cm-content a"
        enabled: true
      - name: "澎湃新闻"
        url: "https://www.thepaper.cn/"
        selector: ".news_title a"
        enabled: true
      
      # 财经金融
      - name: "东方财富网"
        url: "https://finance.eastmoney.com/"
        selector: ".news_list .news_item a"
        enabled: true
      - name: "金融界"
        url: "https://www.jrj.com.cn/"
        selector: ".news-list a"
        enabled: true
      - name: "华尔街见闻"
        url: "https://wallstreetcn.com/"
        selector: ".news-item__title a"
        enabled: true
      - name: "虎嗅"
        url: "https://www.huxiu.com/"
        selector: ".article-item-title a"
        enabled: true
      
      # 科技数码
      - name: "IT之家"
        url: "https://www.ithome.com/"
        selector: ".news_title a"
        enabled: true
      - name: "CNBeta"
        url: "https://www.cnbeta.com/"
        selector: ".title h2 a"
        enabled: true
      - name: "爱范儿"
        url: "https://www.ifanr.com/"
        selector: ".article-title a"
        enabled: true
      - name: "36氪"
        url: "https://36kr.com/"
        selector: ".article-item-title a"
        enabled: true

# AI分析参数
analyzer:
  max_keywords: 50                # 增加关键词发现数量（从25到50）
  min_frequency: 2                # 关键词最小出现次数保持不变
  sentiment_weight: 0.2           # 情感分析权重保持不变
  trend_weight: 0.4               # 趋势分析权重保持不变
  frequency_weight: 0.4           # 词频权重保持不变
  
  # 多源数据融合配置
  source_weights:
    # 不同类型源的权重
    newsnow_api: 1.0              # NewNow API权重最高
    rss: 0.8                      # RSS订阅权重中等
    web_scraper: 0.7              # 略微提高网页抓取权重（从0.6到0.7）
    
    # 特定源的权重调整
    specific_sources:
      "华尔街见闻": 1.2            # 财经新闻权重加成
      "澎湃新闻": 1.1              # 时政新闻权重加成
      "36氪": 1.1                  # 科技新闻权重加成
      "财新网": 1.2                # 新增财经权威媒体权重加成
      "央视新闻": 1.1              # 新增权威媒体权重加成
      "参考消息": 1.1              # 新增国际新闻权重加成
      "联合早报": 1.05             # 新增国际新闻权重加成

# 自适应学习配置
learning:
  enabled: true
  history_days: 14                # 增加学习历史天数（从7到14）
  auto_adjust_weights: true
  
  # 多源学习策略
  source_performance_tracking: true  # 跟踪各源表现
  dynamic_source_weighting: true     # 动态调整源权重

# 通知配置
notification:
  enabled: false
  platforms:
    feishu:
      enabled: false
      webhook_url: ""
    wework:
      enabled: false
      webhook_url: ""
    dingtalk:
      enabled: false
      webhook_url: ""
    telegram:
      enabled: false
      bot_token: ""
      chat_id: ""

# 输出配置
output:
  html_report: true
  json_report: true
  console_output: true
  
  # 增强输出选项
  source_statistics: true          # 包含数据源统计
  coverage_analysis: true          # 包含覆盖度分析
  
# 监控平台（兼容原配置）
platforms:
  # 保持原有配置，确保兼容性
  - id: "toutiao"
    name: "今日头条"
  - id: "baidu"
    name: "百度热搜"
  - id: "weibo"
    name: "微博热搜"
  - id: "zhihu"
    name: "知乎热榜"
  - id: "douyin"
    name: "抖音热搜"
  - id: "bilibili-hot-search"
    name: "B站热搜"
  - id: "wallstreetcn-hot"
    name: "华尔街见闻"
  - id: "thepaper"
    name: "澎湃新闻"

# 扩展数据源映射（覆盖你提到的URL）
extended_sources:
  # 保持原有配置，已在主数据源中添加了完整覆盖
  # 传统媒体
  traditional_media:
    - name: "新浪新闻"
      search_url: "https://search.sina.com.cn/?q={}&from=channel&ie=utf-8"
      rss_url: "http://rss.sina.com.cn/news/allnews/sports.xml"
      priority: "high"
    
    - name: "腾讯新闻"
      search_url: "https://new.qq.com/search?query={}"
      homepage: "https://news.qq.com/"
      priority: "high"
    
    - name: "网易新闻"
      search_url: "https://www.163.com/search?keyword={}"
      rss_url: "http://news.163.com/special/00011K6L/rss_newstop.xml"
      priority: "high"
    
    - name: "搜狐新闻"
      search_url: "https://search.sohu.com/?query={}&type=news"
      homepage: "https://news.sohu.com/"
      priority: "medium"

  # 财经媒体
  financial_media:
    - name: "财新网"
      search_url: "https://search.caixin.com/search.jsp?q={}"
      rss_url: "http://rss.caixin.com/blog/rss.xml"
      priority: "high"
    
    - name: "36氪"
      search_url: "https://36kr.com/search/articles/{}"
      rss_url: "https://36kr.com/feed"
      priority: "high"
    
    - name: "虎嗅"
      search_url: "https://www.huxiu.com/search.html?type=article&q={}"
      rss_url: "https://www.huxiu.com/rss/0.xml"
      priority: "medium"

  # 社交媒体
  social_media:
    - name: "微信公众号"
      search_url: "https://weixin.sogou.com/weixin?query={}"
      priority: "medium"
    
    - name: "小红书"
      search_url: "https://www.xiaohongshu.com/search_result?keyword={}"
      priority: "medium"
    
    - name: "快手"
      search_url: "https://www.kuaishou.com/search/keyword/{}"
      priority: "low"

  # 垂直领域
  vertical_domains:
    - name: "汽车之家"
      search_url: "https://sou.autohome.com.cn/zonghe?q={}"
      category: "automotive"
      priority: "low"
    
    - name: "懂车帝"
      search_url: "https://www.dongchedi.com/search?q={}"
      category: "automotive"
      priority: "low"

# 使用说明
usage_notes: |
  增强版SmartNewsRadar配置说明：
  
  1. 数据源覆盖：
     - NewNow API：主要热搜数据源（38个源）
     - RSS订阅：传统媒体补充（27个源）
     - 网页抓取：备用方案（17个源，已启用）
  
  2. 权重调整：
     - 不同类型源有不同基础权重
     - 可对特定源进行权重加成
     - 学习系统会动态优化
  
  3. 扩展支持：
     - 支持所有重要新闻源URL
     - 可根据需要启用/禁用特定源
     - 支持优先级和分类管理